import Head from "next/head";
import Image from "next/image";
import Blog from "../components/blog/Blog";
import ContactForm from "../components/contactForm/Contackform";
import AboutMe from "../components/heroSection/about/AboutMe";
import Technologies from "../components/heroSection/about/Technologies";
import HeroSection from "../components/heroSection/HeroSection";
import MyProjects from "../components/myProjects/MyProjects";
import Skills from "../components/skills/Skills";
import styles from "../styles/Home.module.css";

const projects = [
  {
    name: "Locks Craft",
    image: "/locks.png",
    url: "https://locks-draft.netlify.app/",
    clintCode: "https://github.com/sagar-biswas1/locks-craft-client",
    serverCode: "https://github.com/sagar-biswas1/locks-craft-server",
    title: ` Full-stack MERN project.`,
    points: [
      "A web site providing all kind of locks smith service. ",
      "Users need to login for booking a service. ",
      "There ase admin panels for both the user and admin. ",
      " In admin panel admin can create read update and delete data.",
    ],
  },
  {
    name: "Buddy-zone",
    image: "/buddy-zone.png",
    url: "https://buddy-zone.vercel.app/",
    clintCode: "https://github.com/sagar-biswas1/buddy-zone-client-side",
    serverCode: "https://github.com/sagar-biswas1/buddy-zone-server-side",
    title: ` A full-stack social media app`,
    points: [
      "A user can create his/her account. On creation s/he will get a welcome message though his/her email. ",
      "In case one forgets his password s/he can also change his password after getting a confirmation link through email (sendgrid is integrated). ",
      "Users can publish their posts. They can also delete their posts. There is a search functionality for searching the users by name.",
      "In case one User follow others s/he can chat also chat with them in real time(Pusher is integrated here.)",
    ],
  },
  {
    name: "Book's Voice",
    image: "/bookVoice.png",
    url: "https://book-voice.netlify.app/",
    clintCode: "https://github.com/sagar-biswas1/book-voice-client",
    serverCode: "https://github.com/sagar-biswas1/book-voice-server",
    title: "Full-stack MERN project.",

    points: [
      "A book selling website where user can purchase a book.",
      "User needs to login before accessing protected pages.",
      "In the admin panel user can see his/her orders details.",
    ],
  },
  {
    name: "Taxi time",
    image: "/taxi.png",
    url: "https://locks-draft.netlify.app/",
    clintCode: "https://github.com/sagar-biswas1/taxi-time",
    title: " A react based project.",
    points: [
      " A site where an user can book a vehicle for going one place to another.",
      " Implemented react routing, protective routing, user authentication.",
      " Google, Facebook, and Email sign-in/login methods available. ",
    ],
  },
  {
    name: "Dream league",
    image: "/dreamLeague.png",
    url: "https://locks-draft.netlify.app/",
    clintCode: "https://github.com/sagar-biswas1/dream-league",
    title:
      "A react routing based project where league data is loaded base on api.",
    points: [
      "Users can see information about different types of leagues .",
      "By clicking on the see-details button they can see specific info based on league id.",
      "Banner and logo will dynamically changed in league details page.[default banner is set in case there is not banner provided by API]",
    ],
  },
];

export default function Home() {
  return (
    <div className={(styles.container, styles.background)}>
      <Head>
        <title>Sagar Biswas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <HeroSection />
        {/* <Skills /> */}
        <Technologies />

        <div className="mt-4">
          <MyProjects projects={projects} />
        </div>
        {/* <Blog /> */}
        <div className="p-4">
          <AboutMe />
        </div>
        <ContactForm />
      </main>
    </div>
  );
}
