import Head from "next/head";
import Image from "next/image";
import Blog from "../components/blog/Blog";
import ContactForm from "../components/contactForm/Contackform";
import AboutMe from "../components/heroSection/about/AboutMe";
import HeroSection from "../components/heroSection/HeroSection";
import MyProjects from "../components/myProjects/MyProjects";
import Skills from "../components/skills/Skills";
import styles from "../styles/Home.module.css";

const projects = [
  {
    name: "Locks draft",
    image: "/locks.png",
    url: "https://locks-draft.netlify.app/",
    clintCode: "https://github.com/sagar-biswas1/locks-craft-client",
    serverCode: "https://github.com/sagar-biswas1/locks-craft-server",
    text: `
A web site providing all kind of locks smith service. Where users need to login for booking a service. There ase admin panels for both the user and admin. In admin panel admin can create read update and delete data. `,
  },
  {
    name: "Book's Voice",
    image: "/bookVoice.png",
    url: "https://book-voice.netlify.app/",
    clintCode: "https://github.com/sagar-biswas1/book-voice-client",
    serverCode: "https://github.com/sagar-biswas1/book-voice-server",
    text: `A book selling website where user can purchase a book . S/he need to login before accessing protected pages. In the admin panel user can see his/her orders details.`,
  },
  {
    name: "Taxi time",
    image: "/taxi.png",
    url: "https://locks-draft.netlify.app/",
    clintCode: "https://github.com/sagar-biswas1/taxi-time",
    text: ` A site where an user can book a vehicle for going one place to another.`,
  },
  {
    name: "Dream league",
    image: "/dreamLeague.png",
    url: "https://locks-draft.netlify.app/",
    clintCode: "https://github.com/sagar-biswas1/dream-league",
    text: `A react routing based project where league data is loaded base on api. `,
  },
];

export default function Home() {
  return (
    <div className={(styles.container, styles.background)}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.mai}>
        <HeroSection />
        {/* <Skills /> */}
        <div className="p-4">
          <AboutMe />
        </div>
        <MyProjects projects={projects} />
        {/* <Blog /> */}
        <ContactForm />
      </main>
    </div>
  );
}
