import Head from "next/head";
import Image from "next/image";
import Blog from "../components/blog/Blog";
import ContactForm from "../components/contactForm/Contackform";
import AboutMe from "../components/heroSection/about/AboutMe";
import HeroSection from "../components/heroSection/HeroSection";
import MyProjects from "../components/myProjects/MyProjects";
import Skills from "../components/skills/Skills";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={(styles.container, styles.background)}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.mai}>
        <HeroSection />
        {/* <Skills /> */}
        <div className="p-4">
          <AboutMe />
        </div>
        <MyProjects />
        <Blog />
        <ContactForm />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
